AWSTemplateFormatVersion: 2010-09-09
Description: a207868-des_sec-filing DR Code CI/CD pipeline
Parameters:
  OutputBucket:
    Type: String
  ServiceName:
    Type: String
  ProjectName:
    Type: String
  BuildRoleArn:
    Type: String
  AssetInsightId:
    Type: String
  AppBuildArn:
    Type: String
  ChgLambdaName:
    Type: String
  QAIACBuildArn:
    Type: String
  ProdIACBuildArn:
    Type: String
  GitHubProjectName:
    Type: String
  GitHubBranchName:
    Type: String
  ProdApprovalTopic:
    Type: String
  QAApprovalTopic:
    Type: String
  GitHubSecretToken:
    Type: String
  GitHubOAuthToken:
    Type: String

Mappings:
  RegionMap:
    us-east-1:
      "RegionShortName": "use1"
    us-west-2:
      "RegionShortName": "usw2"

Resources:
  DeploymentPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location:
          Fn::Sub: ${OutputBucket}
        Type: S3
      Name: !Sub
        - a${AssetInsightId}-${ServiceName}-${ProjectName}-deployment-dr-${RegionShort}
        - { RegionShort: !FindInMap [ RegionMap, !Ref 'AWS::Region', RegionShortName ] }
      RoleArn:
        Ref: "BuildRoleArn"
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: tr
                Repo: !Ref GitHubProjectName
                PollForSourceChanges: false
                Branch: !Ref GitHubBranchName
                OAuthToken: !Ref GitHubOAuthToken
              Name: Source
              OutputArtifacts:
                - Name: CONFIG
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref AppBuildArn
              InputArtifacts:
                - Name: CONFIG
              OutputArtifacts:
                - Name: APP
              Name: App-Build
              RunOrder: 1
          Name: App-Build
        - Actions:
          - ActionTypeId:
              Category: Approval
              Owner: AWS
              Provider: Manual
              Version: '1'
            Name: qa-Approval
            Configuration:
              NotificationArn: !Ref QAApprovalTopic
            RunOrder: 1
          Name: qa-approval
        - Actions:
          - ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            Configuration:
              ProjectName: !Ref QAIACBuildArn
            InputArtifacts:
              - Name: APP
            OutputArtifacts:
              - Name: QAIACOUT
            Name: qa-IAC-Build
            RunOrder: 1
          Name: qa-app-Deploy
        - Actions:
          - ActionTypeId:
              Category: Approval
              Owner: AWS
              Provider: Manual
              Version: '1'
            Name: prod-dev-Approval
            Configuration:
              NotificationArn: !Ref QAApprovalTopic
            RunOrder: 1
          Name: prod-dev-approval
        - Actions:
          - ActionTypeId:
              Category: Approval
              Owner: AWS
              Provider: Manual
              Version: '1'
            Name: prod-ops-Approval
            Configuration:
              NotificationArn: !Ref ProdApprovalTopic
            RunOrder: 1
          Name: prod-ops-approval
        - Actions:
          - ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            Configuration:
              ProjectName: !Ref ProdIACBuildArn
            InputArtifacts:
              - Name: APP
            OutputArtifacts:
              - Name: IACOUT
            Name: prod-IAC-Build
            RunOrder: 1
          Name: prod-app-Deploy

Outputs:
  PipelineArn:
    Description: Deployment Pipeline ARN
    Value: !Ref DeploymentPipeline
